/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: dfecaf23dea6174c79b2b6686c6ed6eb)
interface __BaseEnv_Env {
	DB: D1Database;
	RATE_LIMITER: DurableObjectNamespace<import("./index").RateLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RateLimiter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
